using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using System.Text.RegularExpressions;

namespace OOTItemTracker
{
    /// <summary>
    /// Represents a map for the memory of an OOT save file.
    /// </summary>
    public class MemoryMap
    {
        public Dictionary<SceneIndex, List<OOTItem>> itemsByScene;
        public string[] knownDuds = new string[] {
            "Collectable Heart Piece: { SceneIndex: Kokiri_Forest Type: Collectable Heart Piece Item:  Index: 223 }",
            "Chest: { SceneIndex: Graveyard Type: Chest Item: Piece of Heart Index: 0 }",
            "Chest: { SceneIndex: Goron_City Type: Chest Item: Bombs Index: 2 }",
            "Chest: { SceneIndex: Goron_City Type: Chest Item: Bombs Index: 1 }",
            "Chest: { SceneIndex: Goron_City Type: Chest Item: Bombs Index: 0 }",
        };
        public string[,] EVENT_TABLE = new string[,]
        {
            {
                "",
                "",
                "",
                "Met Deku Tree",
                "",
                "Played Saria's Song for Mido as Adult",
                "Used Blue Warp in Gohma's Lair",
                "",
                "Obtained Kokiri Emerald & Deku Tree Dead",
                "Spoke to Saria After Deku Tree's Death",
                "Deku Tree Opened Mouth",
                "Showed Mido Sword & Shield",
                "Complained About Mido to Saria",
                "First Spoke to Mido",
                "",
                "",
            },
            {
                "",
                "Won the Cow in Malon's Race",
                "Destroyed the Royal Family's Tomb",
                "Spoke to Mido After Deku Tree's Death",
                "Rented Horse From Ingo",
                "",
                "Obtained Kokiri's Emerald",
                "Obtained Epona",
                "Great Deku Tree is Dead",
                "Invited to Sing With Child Malon",
                "Spoke to Child Malon at Ranch",
                "Talon Fled Hyrule Castle",
                "Woke Talon",
                "*Obtained Pocket Egg",
                "Spoke to Ingo at Ranch before Talon returns",
                "Spoke to Child Malon at Castle or Market",
            },
            {
                "Death Mountain Erupted",
                "",
                "[Ref. by Code Table]",
                "[Ref. by Code Table]",
                "[Ref. by Code Table]",
                "[Ref. by Code Table]",
                "",
                "",
                "",
                "",
                "Completed Dodongo's Cavern",
                "",
                "Bombed Dodongo's Cavern Entrance",
                "",
                "[Ref. by Code Table]",
                "[Ref. by Code Table]",
            },
            {
                "",
                "",
                "",
                "Finished Nabooru Battle",
                "Began Nabooru Battle",
                "Offered Fish to Jabu-Jabu",
                "Opened Entrance to Zora's Domain",
                "*Obtained Silver Scale",
                "Obtained Zora's Sapphire",
                "",
                "",
                "",
                "King Zora Moved Aside",
                "",
                "*Obtained Ruto's Letter",
                "Spoke to a Zora",
            },
            {
                "Entered the Master Sword Chamber",
                "Caught by Hyrule Castle Guards",
                "Rainbow Bridge Built by Sages",
                "",
                "Opened the Door of Time",
                "Obtained Water Medallion",
                "Obtained Fire Medallion",
                "Obtained Forest Medallion",
                "",
                "",
                "Pulled Master Sword from Pedestal",
                "",
                "*Obtained Ocarina of Time",
                "[Ref. by Code Table]",
                "[Ref. by Code Table]",
                "*Obtained Zelda's Letter",
            },
            {
                "",
                "",
                "",
                "[Ref. by Code Table]",
                "*Learned Song of Storms",
                "*Learned Sun's Song",
                "*Learned Zelda's Lullaby",
                "",
                "",
                "",
                "*Sheik Moved From Sword Pedestal",
                "*Learned Nocturne of Shadow",
                "",
                "*Learned Serenade of Water",
                "*Learned Bolero of Fire",
                "*Learned Minuet of Forest",
            },
            {
                "Spoke to Kaepora Gaebora by Lost Woods",
                "",
                "",
                "",
                "Spoke to Talon After Saving Ranch",
                "Woke Talon in Kakariko",
                "Restored Lake Hylia's Water",
                "Played Gerudo Archery Minigame",
                "Drained Well in Kakariko Village",
                "",
                "Played Song of Storms in Windmill",
                "",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "Began Ganondorf Battle",
                "Began Bongo Bongo Battle",
                "Began Barinade Battle",
                "Began Twinrova Battle",
                "Began Morpha Battle",
                "Began Volvagia Battle",
                "Began Phantom Ganon Battle",
                "Began King Dodongo Battle",
                "Began Gohma Battle",
            },
            {
                "Paid Back Bunny Hood Fee",
                "Paid Back Spooky Mask Fee",
                "Paid Back Skull Mask Fee",
                "Paid Back Keaton Mask Fee",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "Bridge Unlocked (After Zelda Escape Cutscene)",
                "",
                "Zelda Fled Hyrule Castle",
            },
            {
                "",
                "",
                "",
                "Played Song for Scarecrow as Adult",
                "",
                "",
                "",
                "",
                "",
                "Spoke to Cursed Man in Skulltula House",
                "Nabooru Captured by Twinrova",
                "Spoke to Nabooru in Spirit Temple",
                "Rescued Green Carpenter",
                "Rescued Blue Carpenter",
                "Rescued Yellow Carpenter",
                "Rescued Red Carpenter",
            },
            {
                "",
                "",
                "Completed Spirit Trial",
                "*Learned Requiem of Spirit",
                "",
                "Bongo Bongo Escaped Well",
                "*Learned Song of Time",
                "Entered Deku Tree",
                "Entered Temple of Time",
                "Entered Goron City",
                "Entered Hyrule Castle",
                "Entered Zora's Domain",
                "Entered Kakariko Village",
                "",
                "Entered Death Mountain Trail",
                "Entered Hyrule Field",
            },{
                "Completed Light Trial",
                "Completed Fire Trial",
                "Completed Shadow Trial",
                "Completed Water Trial",
                "Completed Forest Trial",
                "Entered Ganon's Castle (Exterior)",
                "Entered Death Mountain Crater",
                "Entered Desert Colossus",
                "Entered Zora's Fountain",
                "Entered Graveyard",
                "Entered Jabu-Jabu's Belly",
                "Entered Lon Lon Ranch",
                "Entered Gerudo's Fortress",
                "Entered Gerudo Valley",
                "Entered Lake Hylia",
                "Entered Dodongo's Cavern",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "Demo_Effect, Temple of Time Warp in blue aura + sfx the first time you spawn as Adult",
                "Obtained Spirit Medallion",
                "Watched Ganon's Tower Collapse / Caught by Gerudo",
                "Spoke to Deku Tree Sprout",
                "Sheik, Spawned at Master Sword Pedestal as Adult",
                "Returned to Temple of Time With All Medallions",
                "Dispelled Ganon's Tower Barrier",
                "",
                "*Spoke to Saria on Lost Woods Bridge",
                "Nabooru Ordered to Fight by Twinrova",
            },
            {
                "",
                "*Obtained Skulltula House's Piece of Heart",
                "*Obtained Skulltula House's Bombchu",
                "*Obtained Giant's Wallet",
                "*Obtained Stone of Agony",
                "*Obtained Adult's Wallet",
                "",
                "",
                "",
                "*Played Song of Storms for Frogs",
                "*Played Song of Time for Frogs",
                "*Played Saria's Song for Frogs",
                "*Played Sun's Song for Frogs",
                "*Played Epona's Song for Frogs",
                "*Played Zelda's Lullaby for Frogs",
                "*Obtained Frogs' Piece of Heart",
            }
        };
        public string[,] ITEM_GET_TABLE = new string[,]
        {
            {
                "*Obtained Gerudo Quiver Upgrade",
                "*Obtained Kakariko Quiver Upgrade",
                "",
                "*Obtained Bottle From Cucco Lady",
                "*Obtained Heart Piece From Grotto Scrub",
                "Bought Upper-Left Bombchu (Right Shelf)",
                "Bought Lower-Left Bombchu (Left Shelf)",
                "Bought Upper-Right Bombchu (Left Shelf)",
            },
            {
                "Bought Lower-Right Bombchu (Right Shelf)",
                "Bought Lower-Left Bombchu (Right Shelf)",
                "Bought Upper-Left Bombchu (Left Shelf)",
                "Bought Lower-Right Bombchu (Left Shelf)",
                "Bought Upper-Right Bombchu (Right Shelf)",
                "*Super Cucco Milk Bottle",
                "",
                ""
            },
            {
                "*Obtained Stage Deku Nut Upgrade",
                "*Obtained Stage Deku Stick Upgrade",
                "*Obtained Deku Seed Bag Upgrade",
                "",
                "",
                "*Obtained Nayru's Love",
                "*Obtained Din's Fire",
                "*Obtained Farore's Wind",
            },
            {
                "*Obtained Heart Piece From Skullkids",
                "*Obtained Heart Piece From Skullkid",
                "*Obtained Heart Piece From Man on Roof",
                "",
                "Item – Deku Seeds",
                "",
                "",
                "*Obtained Heart Piece From Lake Researcher",
            },
            {
                "",
                "*Obtained Cojiro From Cucco Lady",
                "",
                "*Obtained Pocket Egg From Cucco Lady",
                "",
                "Obtained Mask of Truth",
                "",
                "",
            },
            {
                "",
                "Obtained Bunny Hood",
                "Obtained Spooky Mask",
                "Obtained Skull Mask",
                "Obtained Keaton Mask",
                "",
                "",
                "",
            },
            {
                "Obtained Mask of Truth",
                "",
                "",
                "",
                "Sold Bunny Hood / Unlocked Extra Masks",
                "Sold Spooky Mask / Unlocked Bunny Hood",
                "Sold Skull Mask / Unlocked Spook Mask",
                "Sold Keaton Mask / Unlocked Skull Mask",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "Obtained Poacher's Saw From Fado",
                "Obtained Odd Potion From Granny",
            }
        };
        public string[,] INF_TABLE = new string[,]
        {
            {
                "",
                "",
                "",
                "Met Mido",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "Spoke to Saria in Saria's House",
                "",
                "Complained About Mido to Saria",
                "",
                "Spoke to Saria About Obtaining a Fairy",
                "Greeted by Saria",
            },
            {
                "",
                "Spoke to Kokiri Girl by Jumping Stones",
                "",
                "",
                "",
                "",
                "Told Mido Saria Won't Return",
                "",
            },
            {
                "",
                "",
                "Met Mido in Lost Woods as Adult",
                "",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "Spoke to Girl About Training Center",
            },
            {
                "",
                "Spoke to Kokiri Girl on Shop Awning",
                "",
                "Spoke to Kokiri Boy Pulling Grass",
                "",
                "Spoke to Kokiri Boy Guarding Forest Exit",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "Spoke to Boy on Bed in Mido's House",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "Spoke to Know-It-All Bro. About Temple",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "Spoke to Girl in Saria's House",
                "",
            },
            {
                "",
                "",
                "",
                "Spoke to Dying Knight",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "Spoke to Deku Tree Sprout once (after cutscene)",
                "",
                "",
                "",
                "",
                "Spoke to Know-It-All Bro. About Saria",
                "",
            },
            {
                "",
                "Spoke to Talon in Lon Lon Ranch House",
                "",
                "",
                "",
                "",
                "",
                "",
            },
            {
                "Soldier Wears Keaton Mask",
                "Spoke to Gate Guard About Mask Shop",
                "",
                "",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "Entered Hyrule Castle",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "Child Malon Said Epona Was Scared of You",
                "Met Child Malon at Castle or Market",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "Spoke to Ingo Once as Adult",
                "",
                "",
            },
            {
                "Met Ingo at Ranch",
                "",
                "",
                "Met Ingo at Ranch before Talon returns",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "Rode any horse at Ingo's Ranch",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "Spoke to Carpenter Boss by Tent",
                "Spoke to Fado in Kokiri Forest as Child",
                "",
                "",
                "Spoke to Malon After Saving Ranch",
            },
            {
                "Spoke to Fado at the start of the game",
                "Met Poe Collector in Ruined Market",
                "",
                "",
                "",
                "",
                "Met Medigoron as Adult",
                "Met Medigoron as Child",
            },
            {
                "",
                "Spoke to Thin Lady After Zelda's Escape (DBG)",
                "Spoke to Blue Jokester in Market (DBG)",
                "Spoke to Itchy Lady after Malon leaves town",
                "Spoke to Blue Jokester in Market (1.0) / Dog Lady as Adult (DBG)",
                "Spoke to Red Jokester in Market",
                "Spoke to Thin Lady After Zelda's Escape (1.0)",
                "Spoke to Thin Lady by Bombchu Bowling",
            },
            {
                "Spoke to Old Man by Bombchu Bowling",
                "Spoke to Old Woman by Market Fountain",
                "Spoke to Thin Man by Market Target Shop",
                "Spoke to Thief After Zelda's Escape",
                "Spoke to Burly Man After Zelda's Escape",
                "Spoke to Burly Man About Talon Search",
                "Spoke to Fat Woman After Zelda's Escape",
                "Spoke to Fat Woman by Market Potion Shop",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "Spoke to Goron by Bomb Flowers",
                "",
                "",
                "",
            },
            {
                "",
                "Spoke to Goron by Woods Exit",
                "",
                "",
                "Spoke to Goron Hiding Stick",
                "",
                "",
                "Spoke to Goron at Cavern",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "Spoke to Ruby-Crazy Goron",
                "",
                "",
                "",
                "Spoke to Goron at Entrance",
            },
            {
                "",
                "Spoke to Goron Link",
                "",
                "Stopped Goron Link's Rolling",
                "Spoke to Goron Link About Volvagia",
                "",
                "*Obtained Fire Tunic from Goron Link",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "*Received Goron City Bomb Bag Upgrade",
                "",
                "",
                "",
                "Met Darunia in Fire Temple",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "Met Darunia in Goron City",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "Spoke to Zora Swimming Behind Zora Shop",
                "Spoke to Zora Beside Zora Shop?",
            },
            {
                "",
                "",
                "",
                "Spoke to Zora near Zora Shop",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "*Obtained Zora Tunic",
                "Thawed King Zora",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            },
            {
                "Ruto in JJ, Spawns on F1 instead of B1",
                "Ruto in JJ (M6) Kidnapped",
                "Ruto in JJ (M6) On Sapphire platform",
                "Ruto in JJ (?) wants to be thrown to Sapphire",
                "Ruto in JJ (M10) Can Be Escorted",
                "Ruto in JJ (M3) Talk First Time",
                "Ruto in JJ (M2) Meet Ruto",
                "Ruto in JJ (M7) On Blue Switch",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "Refused Nabooru",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "Spoke to Carpenter Boss's Wife as Adult",
                "Spoke to Carpenter Boss's Wife as Child",
                "Spoke to Man in Impa's as Adult",
                "Spoke to Man in Impa's at Night",
                "Spoke to Man in Impa's in Day",
            },
            {
                "Running Man Suggested a Race",
                "",
                "",
                "",
                "",
                "",
                "",
                "Spoke to Green Carpenter in Tent",
            },
            {
                "",
                "Spoke to Blue Carpenter in Tent",
                "",
                "",
                "",
                "Spoke to Carpenter Boss in Kakariko",
                "",
                "Spoke to Carpenter Boss in Valley",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            },
            {
                "Caught Cucco Behind Potion Shop",
                "Caught Cucco Near Skulltula House",
                "Caught Cucco in Crate",
                "Caught Cucco Behind Windmill",
                "Caught Cucco Near Cucco Pen",
                "Caught Cucco Near Bazaar",
                "Caught Cucco Near Hyrule Field Entrance",
                "*Get Magic Container",
            },
            {
                "*Spoke to Cursed Man With 10 Tokens",
                "Met Cursed Man in Skulltula House",
                "",
                "",
                "*Obtained Grotto Deku Nut Upgrade",
                "*Obtained Lost Woods Deku Stick Upgrade",
                "*Obtained Heart Piece for Finding Richard",
                "*Gerudo Archery Heart Piece",
            },
            {
                "Entered Ganon's Castle (Collapsing)",
                "Entered Ganon's Tower (Collapsing)",
                "Entered Ganon's Castle",
                "Entered Thieves' Hideout",
                "Entered Gerudo Training Ground",
                "Entered Ganon's Tower",
                "Entered Ice Cavern",
                "Entered Bottom of the Well",
            },
            {
                "Entered Shadow Temple",
                "Entered Spirit Temple",
                "Entered Water Temple",
                "Entered Fire Temple",
                "Entered Forest Temple",
                "Entered Jabu-Jabu's Belly",
                "Entered Dodongo's Cavern",
                "Entered Deku Tree",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            },
            {
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            },
            {
                "(Reset upon acquiring sword)",
                "(Reset upon acquiring sword)",
                "(Reset upon acquiring sword)",
                "(Reset upon acquiring sword)",
                "(Reset upon acquiring sword)",
                "(Reset upon acquiring sword)",
                "(Reset upon acquiring sword)",
                "(Reset upon acquiring sword)",
            },
            {
                "(Reset upon acquiring sword)",
                "(Reset upon acquiring sword)",
                "(Reset upon acquiring sword)",
                "(Reset upon acquiring sword)",
                "(Reset upon acquiring sword)",
                "(Reset upon acquiring sword)",
                "(Reset upon acquiring sword)",
                "Swordless (Master Sword Knocked Away)",
            }
        };


        public OOTEvent[] events;

        public IEnumerable<OOTItem> items
        {
            get
            {
                foreach(var scene in itemsByScene)
                {
                    foreach(var item in scene.Value)
                    {
                        yield return item;
                    }
                }
            }
        }

        public void LoadItems()
        {
            //load item list
            List<OOTItem> itemList = new List<OOTItem>();

            //scan items from item files
            string[] lines = File.ReadAllLines("items.txt");
            foreach(var line in lines)
            {
                itemList.Add(OOTItem.Parse(line));
            }

            //assemble items into dictionary
            itemsByScene = new Dictionary<SceneIndex, List<OOTItem>>();
            for(int i = 0; i < 101; i++)
            {
                itemsByScene.Add((SceneIndex)i, new List<OOTItem>());
            }
            foreach(var item in itemList)
            {
                itemsByScene[item.sceneIndex].Add(item);
            }
            File.WriteAllLines("items.txt", items.Select(x => ((int)x.sceneIndex).ToString() + ": " + x.line).ToArray());

            //load events
            List<OOTEvent> events = new List<OOTEvent>();

            //load event table
            for(int i = 0; i < EVENT_TABLE.GetLength(0); i++)
            {
                for(int j = 0; j < EVENT_TABLE.GetLength(1); j++)
                {
                    string e = EVENT_TABLE[i, j];
                    if(e.StartsWith("*"))
                    {
                        int x = i * 2 + 1;
                        int y = 0xF - j;
                        if(y > 7)
                        {
                            y += -8;
                            x--;
                        }
                        events.Add(new OOTEvent(OOTEvent.Table.EventTable, e.Remove(0, 1), x, y));
                    }
                }
            }

            //load item get table
            for(int i = 0; i < ITEM_GET_TABLE.GetLength(0); i++)
            {
                for(int j = 0; j < ITEM_GET_TABLE.GetLength(1); j++)
                {
                    string e = ITEM_GET_TABLE[i, j];
                    if(e.StartsWith("*"))
                    {
                        events.Add(new OOTEvent(OOTEvent.Table.ItemGetTable, e.Remove(0, 1), i, 7 - j));
                    }
                }
            }

            //load inf table
            for(int i = 0; i < INF_TABLE.GetLength(0); i++)
            {
                for(int j = 0; j < INF_TABLE.GetLength(1); j++)
                {
                    string e = INF_TABLE[i, j];
                    if(e.StartsWith("*"))
                    {
                        events.Add(new OOTEvent(OOTEvent.Table.INFTable, e.Remove(0, 1), i, 7 - j));
                    }
                }
            }

            this.events = events.ToArray();
        }
    }
}
