using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OOTItemTracker
{
    /// <summary>
    /// Scene indicies for OOT
    /// </summary>
    public enum SceneIndex
    {
        Deku_Tree = 000,
        Dondogos_Cavern = 001,
        JabuJabus_Belly = 002,
        Forest_Temple = 003,
        Fire_Temple = 004,
        Water_Temple = 005,
        Spirit_Temple = 006,
        Shadow_Temple = 007,
        Below_the_Well = 008,
        Ice_Cavern = 009,
        Ganons_Tower_Second_Part = 010,
        Geruode_Training_Grounds = 011,
        Thieves_Hideout = 012,
        Ganons_Tower = 013,
        Ganons_Tower_Floor_beneath_boss_chamber = 014,
        Ganons_Tower_Crumbling_Exit = 015,
        Treasure_Chest_Shop = 016,
        Deku_Tree_Boss = 017,
        Dondogo_Cavern_Boss = 018,
        JabuJabus_Belly_Boss = 019,
        Forest_Temple_Boss = 020,
        Fire_Temple_Boss = 021,
        Water_Temple_Boss = 022,
        Spirit_Temple_Middle_Boss = 023,
        Shadow_Temple_Boss = 024,
        Second_To_Last_Boss_Ganondorf = 025,
        Ganondorf_Death_Scene = 026,
        Market_Entrance_Day = 027,
        Market_Entrance_Night = 028,
        Market_Entrance_Adult = 029,
        Back_Alley_Day = 030,
        Back_Alley_Night = 031,
        Market_Day = 032,
        Market_Night = 033,
        Market_Adult = 034,
        Temple_of_Time_Outside_Day = 035,
        Temple_of_Time_Outside_Night = 036,
        Temple_of_Time_Outside_Adult = 037,
        Know_it_all_Brothers = 038,
        House_of_Twins = 039,
        Midos_House = 040,
        Sarias_House = 041,
        Kakariko_Village_House = 042,
        Back_Alley_Village_House = 043,
        Kakariko_Bazaar = 044,
        Kokiri_Shop = 045,
        Goron_Shop = 046,
        Zora_Shop = 047,
        Kakariko_Potion_Shop = 048,
        Market_Potion_Shop = 049,
        Bombchu_Shop = 050,
        Happy_Mask_Shop = 051,
        Links_House = 052,
        Puppy_Womans_house_in_market = 053,
        Stables = 054,
        Impas_House = 055,
        Lake_Hylia_Labatory = 056,
        Carpenters_Tent = 057,
        Dampes_Hut = 058,
        Great_Fairy_Fountain = 059,
        Small_Fairy_Fountain = 060,
        Magic_Fairy_Fountain = 061,
        Grottos = 062,
        Grave_1 = 063,
        Grave_2 = 064,
        Royal_Familys_Tomb = 065,
        Shooting_Gallery = 066,
        Temple_of_Time_Inside = 067,
        Chamber_of_Sages = 068,
        Castle_Courtyard_Day = 069,
        Castle_Courtyard_Night = 070,
        Cutscene_Map = 071,
        Dampes_Grave = 072,
        Fishing_Pond = 073,
        Zeldas_Courtyard = 074,
        Bowling_Alley = 075,
        Talons_House = 076,
        Lotso_Pots = 077,
        Grannys_Potion_Shop = 078,
        Final_Battle_against_Ganon = 079,
        Skulltula_House = 080,
        Hyrule_Field = 081,
        Kakariko_Village = 082,
        Graveyard = 083,
        Zora_River = 084,
        Kokiri_Forest = 085,
        Sacred_Forest_Meadow = 086,
        Lake_Hylia = 087,
        Zoras_Domain = 088,
        Zoras_Fountain = 089,
        Gerudo_Valley = 090,
        Lost_Woods = 091,
        Desert_Collusus = 092,
        Gerudos_Fortress = 093,
        Haunted_Wasteland = 094,
        Hyrule_Castle = 095,
        Death_Mountain = 096,
        Death_Mountain_Crater = 097,
        Goron_City = 098,
        Lon_Lon_Ranch = 099,
        Ganons_Tower_Outside = 100,
    }
}